name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'pophubup'
        reponame: 'test1'
        token:  ${{ secrets.GITHUB_TOKEN  }}
